DROP DATABASE IF EXISTS twitter;
CREATE DATABASE twitter;
USE twitter;
DROP TABLE IF EXISTS Tweets;
CREATE TABLE Tweets (
  created_at VARCHAR(300),
  id BIGINT,
  id_str VARCHAR(300),
  text VARCHAR(300),
  source VARCHAR(300),
  truncated BOOL,
  in_reply_to_status_id BIGINT,
  in_reply_to_user_id BIGINT,
  user_id BIGINT,
  user_id_str VARCHAR(300),
  user_name VARCHAR(300),
  user_screen_name VARCHAR(300),
  user_location VARCHAR(300),
  user_url VARCHAR(300),
  user_description VARCHAR(300),
  user_protected BOOL,
  user_verified BOOL,
  user_follower_count BIGINT,
  user_friends_count BIGINT,
  user_listed_count BIGINT,
  user_favorites_count BIGINT,
  user_statuses_count BIGINT,
  user_created_at VARCHAR(300),
  user_profile_image_url_https VARCHAR(300),
  user_default_profile BOOL,
  user_default_profile_image BOOL,
  user_withheld_in_countries VARCHAR(300),
  user_geo_enabled BOOL,
  is_quote_status BOOL,
  quote_count BIGINT,
  reply_count BIGINT,
  retweet_count BIGINT,
  favorite_count BIGINT,
  entities_user_mentions VARCHAR(2000),
  entities_hashtags VARCHAR(2000),
  entities_urls VARCHAR(2000),
  entities_symbols VARCHAR(2000),
  favorited BOOL,
  retweeted BOOL,
  filter_level VARCHAR(2000),
  lang VARCHAR(300),
  text_no_rt VARCHAR(300),
  text_no_handle VARCHAR(300),
  text_no_hashtags VARCHAR(300),
  text_no_urls VARCHAR(300),
  text_no_punct VARCHAR(300),
  text_lower VARCHAR(300),
  nltk DECIMAL(38,38),
  vader DECIMAL(38,38),
  PRIMARY KEY(id)
);